
@baseUrl_local = http://localhost:3055
@baseUrl_Remote = https://miragebackend-saag-dev.fl0.io
@authToken = {{login.response.body.token}}
###
# @name login
POST {{baseUrl_local}}/user/login HTTP/1.1
Content-Type: application/json

{ 
	"username":"catastones",
    "password":"123456"    
}
###
GET {{baseUrl_local}}/categorias HTTP/1.1

###
POST {{baseUrl_local}}/categorias HTTP/1.1
Content-Type: application/json
x-acces-token: {{authToken}}

{ 
	"name":"motherboard"   
}
###
DELETE {{baseUrl_local}}/categorias/651b49f1ca31694fa4a5fc76 HTTP/1.1
###
PUT  {{baseUrl_local}}/categorias HTTP/1.1
Content-Type: application/json
x-acces-token: {{authToken}}

 {
    "_id": "651b24b864473350ffc86370",
    "name": "Smart Watch"
  }