
@baseUrl_local = http://localhost:3055
@baseUrl_Remote = https://miragebackend-saag-dev.fl0.io
@authToken = {{login.response.body.token}}
###
# @name login
POST {{baseUrl_local}}/user/login HTTP/1.1
Content-Type: application/json

{ 
	"username":"catastones",
    "password":"123456"    
}
###
###
GET {{baseUrl_local}}/productos HTTP/1.1
###
GET {{baseUrl_local}}/productos/byid/65439c0e056f71e50764ae50 HTTP/1.1
###
###
GET {{baseUrl_Remote}}/productos/categoria/TV HTTP/1.1
###
POST {{baseUrl_Remote}}/productos HTTP/1.1
Content-Type: application/json
x-acces-token: {{authToken}}

{ 
	"categoria":"SmartPhone",
        "url_image":"",
        "modelo":"iPhone 11 Pro Max",
        "marca":"Apple",
        "descripcion":"6.5-inch Super Retina XDR OLED display, Triple 12MP Ultra Wide, Wide, and Telephoto cameras, A13 Bionic chip, Face ID, and iOS 13","stock":10,"price":1099

}
###
DELETE {{baseUrl_local}}/productos/65439c0e056f71e50764ae50 HTTP/1.1
x-acces-token: {{authToken}}
###
PUT {{baseUrl_local}}/productos HTTP/1.1
Content-Type: application/json
x-acces-token: {{authToken}}

{ 
    "_id": "651c651af1774eef38dbb162",
	"categoria":"TV", 
    "modelo":"LG UHD LED AI ThinQ 4K 65'",
    "marca":"LG",
    "descripcion":{
        "pantalla":"PANEL 4K 65'",
        "Resolucion":"3840 x 2.160",
        "Procesador":"4K Procesador Inteligente α5",
        "SO":"webOS 6.0",
        "USB":2,
        "HDMI":3        
    },
    "stock":3,     
    "precio":699.999,
    "url_image":"https://www.lg.com/ar/images/televisores/md07540656/gallery/Z-01.jpg"
}
###
###
POST {{baseUrl_local}}/productos/lotes/ HTTP/1.1
Content-Type: application/json
x-acces-token: {{authToken}}

{
    "productos":[
 
    {"categoria":"Consola","url_image":"","marca":"Sony","modelo":"PlayStation 4 Pro","descripcion":"The world's most powerful console with 4K gaming and entertainment, HDR technology, and faster frame rates.","precio":399.99,"stock":10},
    {"categoria":"Consola","url_image":"","marca":"Microsoft","modelo":"Xbox One X","descripcion":"The world's most powerful console with 4K gaming and entertainment, HDR technology, and faster frame rates.","precio":499.99,"stock":10},
    {"categoria":"Consola","url_image":"","marca":"Nintendo","modelo":"Switch","descripcion":"The Nintendo Switch is a hybrid console that can be used as both a home console and a portable device.","precio":299.99,"stock":10},
    {"categoria":"Consola","url_image":"","marca":"Sony","modelo":"PlayStation 4 Slim","descripcion":"The slimmed down version of the PlayStation 4, with improved power efficiency and a smaller form factor.","precio":299.99,"stock":10},
    {"categoria":"Consola","url_image":"","marca":"Microsoft","modelo":"Xbox One S","descripcion":"The slimmed down version of the Xbox One, with improved power efficiency and a smaller form factor.","precio":299.99,"stock":10},
    {"categoria":"Consola","url_image":"","marca":"Nintendo","modelo":"Wii U","descripcion":"The Wii U is a home console that features a unique tablet-like controller and a variety of exclusive games.","precio":199.99,"stock":10},
    {"categoria":"Consola","url_image":"","marca":"Sony","modelo":"PlayStation 3","descripcion":"The PlayStation 3 is a home console that features a variety of exclusive games and a Blu-ray player.","precio":199.99,"stock":10},
    {"categoria":"Consola","url_image":"","marca":"Microsoft","modelo":"Xbox 360","descripcion":"The Xbox 360 is a home console that features a variety of exclusive games and a DVD player.","precio":199.99,"stock":10},
    {"categoria":"Consola","url_image":"","marca":"Nintendo","modelo":"Wii","descripcion":"The Wii is a home console that features a variety of exclusive games and a motion-sensing controller.","precio":199.99,"stock":10},
    {"categoria":"Consola","url_image":"","marca":"Sony","modelo":"PlayStation 2","descripcion":"The PlayStation 2 is a home console that features a variety of exclusive games and a DVD player.","precio":149.99,"stock":10}
  
                ]
}




# { 
# 	"categoria":"SmartPhone", 
#     "modelo":"Moto G32",
#     "marca":"Motorola",
#     "descripcion":{
#         "pantalla":"6.5'",
#         "Resolucion":"2400 px x 1080 px",        
#         "SO":"Android 12",
#         "Resolucion_camara_trasera":"50 Mpx",
#         "Resolucion_camara_frontal":"16 Mpx",
#         "RAM":  "6 GB",
#         "ROM":  "128 GB",
#         "SIM_MAX":"1TB"    
#     },
#     "stock":10,     
#     "precio":139.999,
#     "url_image":"https://http2.mlstatic.com/D_NQ_NP_825955-MLU71687252597_092023-V.webp"
# }
# { 
# 	"categoria":"TV", 
#     "modelo":"55 Neo QLED 4K QN85C",
#     "marca":"Samsung ",
#     "descripcion":"Procesador Neural Quantum 4K - Neo Slim",
#     "stock":5,  
    
#     "precio":11,
#     "url_image":""
# }
# { 
# 	"categoria":"TV", 
#     "modelo":"KD-55X80J AR4",
#     "marca":"Sony",
#     "descripcion":{
#         "pantalla":"55 pulgadas",
#         "Resolucion":"3840 x 2.160",
#         "Procesador":"4K HDR Processor X1™",
#         "SO":"Android TV™",
#         "USB":2,
#         "HDMI":4        
#     },
#     "stock":5,     
#     "precio":949.999,
#     "url_image":"https://arsonyb2c.vtexassets.com/arquivos/ids/357168/d4f672c8c1b08401c3fb67cce747b7db.jpg?v=1777105420"
# }
# { 
# 	"categoria":"TV", 
#     "modelo":"LG UHD LED AI ThinQ 4K 65'",
#     "marca":"LG",
#     "descripcion":{
#         "pantalla":"PANEL 4K 65'",
#         "Resolucion":"3840 x 2.160",
#         "Procesador":"4K Procesador Inteligente α5",
#         "SO":"webOS 6.0",
#         "USB":2,
#         "HDMI":3        
#     },
#     "stock":4,     
#     "precio":949.999,
#     "url_image":"https://arsonyb2c.vtexassets.com/arquivos/ids/357168/d4f672c8c1b08401c3fb67cce747b7db.jpg?v=1777105420"
# }