@baseUrl_local = http://localhost:3055

@baseUrl_Remote = https://miragebackend-saag-dev.fl0.io

###
GET {{baseUrl_local}}/categorias HTTP/1.1

###
POST {{baseUrl_Remote}}/categorias HTTP/1.1
Content-Type: application/json

{ 
	"name":"milanesa"   
}
###
DELETE {{baseUrl_Remote}}/categorias/651b49f1ca31694fa4a5fc76 HTTP/1.1
###
PUT  {{baseUrl_Remote}}/categorias HTTP/1.1
Content-Type: application/json

 {
    "_id": "651b24b864473350ffc86370",
    "name": "Smart Watch"
  }